--- #YAML:1.0
abstract: 'Enforce users to fill standard fields when creating a ticket'
author:
  - 'Benjamin Heisig <bheisig@synetics.de>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
requires:
  rt: 4.0.0
  perl: 5.10.0
distribution_type: module
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-MandatoryFields
no_index:
  file:
    - TODO
  directory:
    - html
    - inc
    - t
keywords:
  - RT
  - Request Tracker
  - Mandatory
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/bheisig/rt-extension-mandatoryfields.git
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=RT-Extension-MandatoryFields
  homepage: http://search.cpan.org/~bheisig/RT-Extension-MandatoryFields/
generated_by: Benjamin Heisig <bheisig@synetics.de>
version: 0.7
